name = "iv-mavengang-mcp"
main = "index.js"
compatibility_date = "2025-03-10"
compatibility_flags = ["nodejs_compat"]

[vars]
BASE_URL = "https://mavengang.com/v1"

[[kv_namespaces]]
binding = "OAUTH_KV"
id = "1f62a7a4ae3244d0b00d364e936bd7f3"
preview_id = "440d41db89564c5d876d50c17496d59a"
remote = true

[[kv_namespaces]]
binding = "SESSIONS"
id = "3ccf96101fde4261a114beecef91987c"
preview_id = "86ef0e58247a4f2c9adeeead5dbbec51"

[[durable_objects.bindings]]
name = "MCP_OBJECT"
class_name = "MavenGangMCP"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["MavenGangMCP"]